name: ml_general
channels:
  - conda-forge # Channel necessary for some versions of packages
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pip=23.2.1
  - numpy=1.23.5 # slighly older for umap-learn (np.int issue)
  - pandas=2.0.3  # 2.1.0 is available but throws lots of warnings with other packages
  - scikit-learn=1.5
  - seaborn=0.13.2
  - matplotlib=3.8.3
  - jupyter=1.0
  - cpuonly
  - pytorch=2.0.1
  - torchvision=0.15.2
  - xgboost=2.0.3
  - catboost=1.2.3
  - statsmodels=0.14.1
  - treeinterpreter=0.2.3 # also quite old (but works?)
  - python-graphviz=0.20.1
  - scikit-plot=0.3.7 # This is quite old, not updated (but works)
  - imbalanced-learn=0.11.0
  - bokeh=3.2.2  # plotting as well
  - hdbscan=0.8.33 # most likely to fail
  - umap-learn=0.5.3
  - shap=0.42.1
  - lime=0.2
  - pydotplus=2.0.2 # For decision tree plotting
  - pip:
    - tensorflow==2.13.0
